# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :dynamic

target 'united_cab_driver' do
  config = use_native_modules!
  pod 'GoogleUtilities'
  pod 'FirebaseCoreInternal'
  pod 'SDWebImage', '>= 5.18.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,   # 🚫 disable New Architecture
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
